name: 'Workflow that runs on a event outside github'
on: 
    repository_dispatch:
        types: [test_result]
env: 
    workflow_variable: workflow_value
jobs:
        run_if_failure:
          if: ${{ github.event.client_payload.passed }}
          runs-on: ubuntu-latest
          steps:
            - env:
                MESSAGE: ${{ github.event.client_payload.message }}
                JOJOBA: ${{ github.event.client_payload.message }}
              run: echo $MESSAGE
        
        run_every_time:
          runs-on: ubuntu-latest
          steps:
            - run: | 
                echo ${{ github.event.client_payload.message }}

            - name: 'display workflow variable'
              run: echo ${{ vars.workflow_variable }}

        


