name: 'Workflow that runs on a event outside github'
on: 
    repository_dispatch:
        types: [test_result]
jobs:
        run_if_failure:
          if: ${{ github.event.client_payload.passed }}
          runs-on: ubuntu-latest
          steps:
            - env:
                MESSAGE: ${{ github.event.client_payload.message }}
                JOJOBA: ${{ github.event.client_payload.message }}
              run: echo $MESSAGE
        
        run_every_time:
          runs-on: ubuntu-latest
          steps:
            - name: Step to dispplay payload message
              run: echo ${{ github.event.client_payload.message }}

